image: ubuntu/latest
packages:
  - curl
  - unzip
sources:
  - https://git.sr.ht/~ruivieira/crystal-vesta
tasks:
  - setup: |
      curl -fsSL https://crystal-lang.org/install.sh | sudo bash
  - test: |
      cd crystal-vesta
      shards install --ignore-crystal-version
      crystal spec
      crystal spec
